
exclude: [".ruby-version", "README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
encoding: UTF-8

permalink: /:categories/:title  # url格式
markdown: redcarpet  # markdown引擎
highlighter: pygments

title: 新声音
tagline: Site Tagline
production_url : http://www.xinshengyin.com

navigation:
 - url: /index.html
   title: 首页
 - url: /category/index.html
   title: 分类
 - url: /about/index.html
   title: 关于我

collections:
  category:
    output: true