
exclude: [".ruby-version", "README.md", "Rakefile"]
encoding: UTF-8

permalink: /:categories/:title  # url格式
markdown: redcarpet  # markdown引擎
highlighter: pygments

title: 新声音
tagline: Site Tagline
production_url : http://www.xinshengyin.com

navigation:
 - url: /index.html
   title: 首页
 - url: /category/index.html
   title: 分类
 - url: /about/index.html
   title: 关于我


author :
  name : 宜昌新声音科技有限公司
  e-name: XinShengYin, Inc.
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

 #  Jekyll-Bootstrap 设置
JB :
   version : 0.3.0
   BASE_PATH : false
   ASSET_PATH : /assets/
   archive_path: /archive.html
   categories_path : /categories.html
   tags_path : /tags.html
   atom_path : /atom.xml
   rss_path : /rss.xml
