
include: ["assets/", "CNAME"]
exclude: [".ruby-version", "README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
encoding: UTF-8

permalink: /:categories/:title
markdown: redcarpet
highlighter: pygments

title: 新声音
tagline: Site Tagline
production_url : http://www.xinshengyin.com

navigation:
 - url: /
   title: 首页
 - url: /technique
   title: 技术
 - url: /about
   title: 关于我

collections:
  technique:
    output: true
